"""Initial migration

Revision ID: 62860a6c27e7
Revises: 
Create Date: 2024-07-06 21:53:34.465452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62860a6c27e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_massages_message_id', table_name='massages')
    op.drop_table('massages')
    op.drop_index('ix_posts_post_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index('email', table_name='users')
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_account_account_num', table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_num', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='account_ibfk_1'),
    sa.PrimaryKeyConstraint('account_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_account_account_num', 'account', ['account_num'], unique=True)
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_table('posts',
    sa.Column('post_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='posts_ibfk_1'),
    sa.PrimaryKeyConstraint('post_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_posts_post_id', 'posts', ['post_id'], unique=False)
    op.create_table('massages',
    sa.Column('message_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sent_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['recipent_id'], ['users.user_id'], name='massages_ibfk_2'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name='massages_ibfk_1'),
    sa.PrimaryKeyConstraint('message_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_massages_message_id', 'massages', ['message_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('reciver', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['reciver'], ['account.account_num'], name='transactions_ibfk_3'),
    sa.ForeignKeyConstraint(['sender'], ['account.account_num'], name='transactions_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='transactions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###
